E2Helper.Descriptions["isSquadMember(e:)"] = "Returns 1 is this player is part of a squad."
E2Helper.Descriptions["getSquadID(e:)"] = "Get the ID of the squad this player is part of. Returns -1 if this player is not in one."
E2Helper.Descriptions["doesSquadExist(n)"] = "Returns 1 if the given ID points to a valid squad."
E2Helper.Descriptions["getSquadName(n)"] = "Finds a squad by it's ID and returns the name. Returns a empty string if the squad does not exist."
E2Helper.Descriptions["getSquadColor(n)"] = "Finds a squad by it's ID and returns the color. Returns vec(0) if the squad does not exist."
E2Helper.Descriptions["getSquadMemberCount(n)"] = "Returns the number of members in a squad, or 0 if the squad does not exist."
E2Helper.Descriptions["getSquadMembers(n)"] = "Returns an array of active players associated with the squad ID, or a empty array if the squad does not exist."
E2Helper.Descriptions["getAllSquadIDs()"] = "Returns an array of all available squad IDs."
